name: Build and Test

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package*.json"
      - ".github/workflows/**"
      - "test/**"
      - "fixture/**"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".npmignore"
      - ".vscode/**"

  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package*.json"
      - ".github/workflows/**"
      - "test/**"
      - "fixture/**"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".npmignore"
      - ".vscode/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: DEBUG=eslint:eslint npm run lint -- --ignore-pattern 'fixture/*'

  test:
    name: Testing
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        node-version: [22, 24, 25]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-24.04-arm
            node-version: 24
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test

  bats:
    name: Bats Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:bats
