name: Build and Test

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package*.json'
      - '.github/**/*.yml'
      - 'test/**'
      - 'fixture/**'
      - '*.config.js'
      - '.prettierrc'
      - '.gitignore'
      - '.npmignore'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          dry: true
  audit:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Security check
        run: npm audit --audit-level=high
  lint:
    name: Linting
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: DEBUG=eslint:* npm run lint -- --ignore-pattern 'test/bats/fixture/**/*.js' --cache
      - name: Cache ESLint
        uses: actions/cache@v5
        with:
          path: .eslintcache
          key: eslint-${{ runner.os }}-${{ hashFiles('**/*.js') }}
          restore-keys: |
            eslint-${{ runner.os }}-

  test:
    name: Testing
    needs:
      - audit
      - lint
    strategy:
      fail-fast: true
      matrix:
        node-version: [22, 24, 25]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-24.04-arm
            node-version: 24
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run test -- --coverage --logHeapUsage

  bats:
    name: Bats Tests
    needs:
      - audit
      - lint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run test:bats
